# Catppuccin Mocha color scheme for kitty / tmux

foreground #cdd6f4
background #1e1e2e

# Black
color0  #45475a
color8  #585b70

# Red
color1  #f38ba8
color9  #f38ba8

# Green
color2  #a6e3a1
color10 #a6e3a1

# Yellow
color3  #f9e2af
color11 #f9e2af

# Blue
color4  #89b4fa
color12 #89b4fa

# Magenta
color5  #cba6f7
color13 #cba6f7

# Cyan
color6  #94e2d5
color14 #94e2d5

# White
color7  #bac2de
color15 #a6adc8

# Cursor
cursor #f5e0dc
cursor_text_color #1e1e2e

# Selection highlight
selection_foreground none
selection_background #313244

# URL highlight
url_color #a6e3a1

# Window borders
active_border_color #89b4fa
inactive_border_color #181825
bell_border_color #f9e2af

# Tab bar
tab_bar_style fade
tab_fade 1

active_tab_foreground   #1e1e2e
active_tab_background   #89b4fa
active_tab_font_style   bold

inactive_tab_foreground #cdd6f4
inactive_tab_background #313244
inactive_tab_font_style bold

tab_bar_background #181825
