unbind r
bind r source-file ~/.tmux.conf

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# set vi-mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g mouse on
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc,tmux-256color:Tc"

set-option -g history-limit 500000
set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh

# Enable OSC52 clipboard support
set -g set-clipboard on
set -as terminal-overrides ',*:Ms=\E]52;%p1%s;%p2%s\007'

# theming
set -g status-bg '#1f1e2e'
set -g status-fg '#d2d8f2'
